# Generated by Django 3.2.25 on 2024-03-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saladuser',
            name='profile_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
