# Generated by Django 3.2.25 on 2024-03-27 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240327_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladuser',
            name='testing',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
