# Generated by Django 3.2.25 on 2024-03-28 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_saladuser_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saladuser',
            name='testing',
        ),
        migrations.AddField(
            model_name='saladuser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
