# Generated by Django 5.0.4 on 2024-05-11 03:12

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240328_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crochet_Customer',
            fields=[
                ('saladuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Crochet Customer',
                'verbose_name_plural': 'Crochet Customers',
            },
            bases=('users.saladuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crochet_Employee',
            fields=[
                ('saladuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Crochet Employee',
                'verbose_name_plural': 'Crochet Employees',
            },
            bases=('users.saladuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Salad_Customer',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Salad_Employee',
        ),
        migrations.AlterModelOptions(
            name='salad_customer',
            options={'verbose_name': 'Salad Customer', 'verbose_name_plural': 'Salad Customers'},
        ),
        migrations.AlterModelOptions(
            name='salad_employee',
            options={'verbose_name': 'Salad Employee', 'verbose_name_plural': 'Salad Employees'},
        ),
    ]
